### ISSUE TITLE
Invite all devs to slack channel

### ISSUE THREAD

**Issue by stevenordstrom** [Lunatic-Labs/Operations#1]

**Comment by redeemefy** [comment]
Do we have a particular room for Operations?

**Comment by stevenordstrom** [comment]
Yes, I just set up a channel on the Lunatic Labs slack for operations...
that will let us and the interns communicate with the devs and start issue
tracking... I still have to invite the interns to the Operations project on
Github, waiting for them to tell me their github usernames.

*———————————————————*
Steven G. Nordstrom*, *Ph.D.
Associate Professor and Chair, Department of Computer Sciences
*College of Computing and Technology*
Office: Swang 125
p  615.966.5002 <+16159665002> | e steve.nordstrom@lipscomb.edu

Lipscomb University
One University Park Drive, Nashville, TN 37204
lipscomb.edu/technology  |  t @LipscombCCT <https://twitter.com/LipscombCCT>
[image: Lipscomb University] <http://www.lipscomb.edu/>
